# Generated by Django 4.1.2 on 2023-05-09 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('champion', models.CharField(max_length=12, verbose_name='Чемпион')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('items', models.JSONField(verbose_name='Предметы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
