# Generated by Django 4.1.2 on 2023-05-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0002_alter_build_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='slug',
            field=models.SlugField(default=1, verbose_name='url'),
            preserve_default=False,
        ),
    ]
