# Generated by Django 4.1.2 on 2023-05-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0003_build_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='url'),
        ),
    ]
