# Generated by Django 4.1.2 on 2023-05-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_remove_customuser_пол_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('m', 'Мужчина'), ('f', 'Посудомойка')], default='m', max_length=1, verbose_name='Пол'),
        ),
    ]
